"""Rename specification to specifications relationship in Product model.

Revision ID: 00af18cbf4f6
Revises: 7ade6842801f
Create Date: 2026-06-18 17:13:50.341117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00af18cbf4f6'
down_revision: Union[str, Sequence[str], None] = '7ade6842801f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
