"""Change precision to value field in Coupon model.

Revision ID: 182d9c1e2cf8
Revises: 0865cffd25ed
Create Date: 2026-06-28 23:31:52.397384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182d9c1e2cf8'
down_revision: Union[str, Sequence[str], None] = '0865cffd25ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'value',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
