"""Add UniqueConstraint name&category_id to Product model.

Revision ID: 2a557bf38e62
Revises: a426dd8081fd
Create Date: 2026-06-07 14:32:22.728400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a557bf38e62'
down_revision: Union[str, Sequence[str], None] = 'a426dd8081fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_name_category', 'product', ['name', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_name_category', 'product', type_='unique')
    # ### end Alembic commands ###
