"""Add lazy selectin to parent & children relationships in Category model.

Revision ID: 33270eb6bf20
Revises: 93314dc66eaa
Create Date: 2026-06-02 18:51:04.175376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33270eb6bf20'
down_revision: Union[str, Sequence[str], None] = '93314dc66eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
