"""Add max length to comment field in Review model.

Revision ID: 345f8ca1041d
Revises: 2a557bf38e62
Create Date: 2026-06-08 23:05:22.896972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345f8ca1041d'
down_revision: Union[str, Sequence[str], None] = '2a557bf38e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
