"""add payment table and order payment relationship

Revision ID: 420a202c4a29
Revises: fcfb8b83536c
Create Date: 2026-07-05 18:51:45.452849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '420a202c4a29'
down_revision: Union[str, Sequence[str], None] = 'fcfb8b83536c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_method', sa.Enum('cash', 'yookassa', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'succeeded', 'canceled', 'refunded', name='paymentstatus', native_enum=False), server_default='pending', nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('external_payment_id', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_payment_order_id_order'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payment_order_id'))
    )
    op.create_index(op.f('ix_payment_external_payment_id'), 'payment', ['external_payment_id'], unique=True)
    op.alter_column('order', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'),
               type_=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'canceled', name='orderstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'canceled', name='orderstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_external_payment_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
