"""Add check coupon used count limit constraint to Coupon model.

Revision ID: 54bff2f5ed21
Revises: 182d9c1e2cf8
Create Date: 2026-06-29 01:44:59.209860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bff2f5ed21'
down_revision: Union[str, Sequence[str], None] = '182d9c1e2cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.create_unique_constraint(op.f('uq_coupon_code'), 'coupon', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_coupon_code'), 'coupon', type_='unique')
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    # ### end Alembic commands ###
