"""Add slug field in Product model.

Revision ID: 6dd2f75acf47
Revises: af5f70405924
Create Date: 2026-08-10 10:48:03.289658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd2f75acf47'
down_revision: Union[str, Sequence[str], None] = 'af5f70405924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_product_slug'), 'product', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slug'), table_name='product')
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
