"""Rename specification to specifications relationship in ProductSpecification model.

Revision ID: 7ade6842801f
Revises: 9de0dd2f4441
Create Date: 2026-06-18 17:01:42.612877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ade6842801f'
down_revision: Union[str, Sequence[str], None] = '9de0dd2f4441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
