"""Nullable False for slug fields in Category & Product models.

Revision ID: 8dc39718062e
Revises: 6dd2f75acf47
Create Date: 2026-08-10 11:32:44.493690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc39718062e'
down_revision: Union[str, Sequence[str], None] = '6dd2f75acf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
