"""Add Coupon model.

Revision ID: 93314dc66eaa
Revises: cd4c5f5723be
Create Date: 2026-05-19 19:47:23.360108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93314dc66eaa'
down_revision: Union[str, Sequence[str], None] = 'cd4c5f5723be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='discounttype', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("\n            (\n                discount_type = 'percent'\n                AND value <= 100\n            )\n            OR\n            (\n                discount_type = 'fixed'\n            )\n            ", name='check_coupon_percent_max'),
    sa.CheckConstraint('min_order_amount IS NULL OR min_order_amount >= 0', name='check_coupon_min_order_amount_positive'),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit > 0', name='check_coupon_usage_limit_positive'),
    sa.CheckConstraint('used_count >= 0', name='check_coupon_used_count_positive'),
    sa.CheckConstraint('value > 0', name='check_coupon_value_positive'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon'))
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    # ### end Alembic commands ###
