"""Add lazy selectin to products in Category model.

Revision ID: a426dd8081fd
Revises: 33270eb6bf20
Create Date: 2026-06-03 00:48:05.867030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a426dd8081fd'
down_revision: Union[str, Sequence[str], None] = '33270eb6bf20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
