"""Add Cart model.

Revision ID: a6f5b8460158
Revises: 845758059df4
Create Date: 2026-05-14 16:52:57.498538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a6f5b8460158'
down_revision: Union[str, Sequence[str], None] = '845758059df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cart_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart')),
    sa.UniqueConstraint('user_id', name=op.f('uq_cart_user_id'))
    )
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('product_image', sa.Column('file_key', sa.String(), nullable=False))
    op.create_index('ix_product_one_main_image', 'product_image', ['product_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    op.drop_column('product_image', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_product_one_main_image', table_name='product_image', postgresql_where=sa.text('is_main = true'))
    op.drop_column('product_image', 'file_key')
    op.alter_column('product', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('cart')
    # ### end Alembic commands ###
