"""Add slug field in Category model.

Revision ID: af5f70405924
Revises: 420a202c4a29
Create Date: 2026-08-09 22:31:55.759780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5f70405924'
down_revision: Union[str, Sequence[str], None] = '420a202c4a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
