"""Add max length to file_key field in ProductImage model.

Revision ID: df53dbd93b72
Revises: 345f8ca1041d
Create Date: 2026-06-08 23:43:59.310918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df53dbd93b72'
down_revision: Union[str, Sequence[str], None] = '345f8ca1041d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
