"""Add original_filename, content_type, file_size, width, height fields and add unique=True in file_key field.

Revision ID: df6c4a0fb87f
Revises: df53dbd93b72
Create Date: 2026-06-11 17:02:12.821513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6c4a0fb87f'
down_revision: Union[str, Sequence[str], None] = 'df53dbd93b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('product_image', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('product_image', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('product_image', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('product_image', sa.Column('height', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_product_image_file_key'), 'product_image', ['file_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_image_file_key'), 'product_image', type_='unique')
    op.drop_column('product_image', 'height')
    op.drop_column('product_image', 'width')
    op.drop_column('product_image', 'file_size')
    op.drop_column('product_image', 'content_type')
    op.drop_column('product_image', 'original_filename')
    # ### end Alembic commands ###
