"""Add coupon_id and discount_amount to orders.

Revision ID: e24550e4574c
Revises: 54bff2f5ed21
Create Date: 2026-06-30 17:45:26.554024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24550e4574c'
down_revision: Union[str, Sequence[str], None] = '54bff2f5ed21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('discount_amount', sa.Numeric(precision=7, scale=2), nullable=False))
    op.create_index(op.f('ix_order_coupon_id'), 'order', ['coupon_id'], unique=False)
    op.create_foreign_key(op.f('fk_order_coupon_id_coupon'), 'order', 'coupon', ['coupon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_coupon_id_coupon'), 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_coupon_id'), table_name='order')
    op.drop_column('order', 'discount_amount')
    op.drop_column('order', 'coupon_id')
    # ### end Alembic commands ###
