"""Change user.id ForeignKey to user.username in Review model.

Revision ID: ed18afa3bf96
Revises: 0030d46fd679
Create Date: 2026-06-17 16:20:39.914440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed18afa3bf96'
down_revision: Union[str, Sequence[str], None] = '0030d46fd679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_username', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_review_user_product'), 'review', type_='unique')
    op.create_unique_constraint('uq_review_user_product', 'review', ['user_username', 'product_id'])
    op.drop_constraint(op.f('fk_review_user_id_user'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_user_username_user'), 'review', 'user', ['user_username'], ['username'], ondelete='CASCADE')
    op.drop_column('review', 'user_id')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('review', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_review_user_username_user'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_user_id_user'), 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_review_user_product', 'review', type_='unique')
    op.create_unique_constraint(op.f('uq_review_user_product'), 'review', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('review', 'user_username')
    # ### end Alembic commands ###
