"""Add coupon_id to cart.

Revision ID: fcfb8b83536c
Revises: e24550e4574c
Create Date: 2026-06-30 17:55:07.446539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfb8b83536c'
down_revision: Union[str, Sequence[str], None] = 'e24550e4574c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_cart_coupon_id_coupon'), 'cart', 'coupon', ['coupon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cart_coupon_id_coupon'), 'cart', type_='foreignkey')
    op.drop_column('cart', 'coupon_id')
    # ### end Alembic commands ###
