"""Add RESTRICT foreign key to prevent deletion of categories with products.

Revision ID: 5746165dd3a8
Revises: 5549b6bc15fe
Create Date: 2026-05-12 20:13:56.297795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5746165dd3a8'
down_revision: Union[str, Sequence[str], None] = '5549b6bc15fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_category_id_category'), 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_category_id_category'), 'product', 'category', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_category_id_category'), 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_category_id_category'), 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
